spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/todo"
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  error:
    include-message: always
jwt:
  secret: bulentyilmazbulentyilmazbulentyilmazbulentyilmazbulentyilmazbulentyilmazbulentyilmazbulentyilmaz